На карте Беларуси имеется N городов,каждый с каждым связывает дорога определенной протяженности.
Напишите функцию на языке “Python” нахождения ближайшего маршрута из двух городов случайно выбранных из N.
Матрица расстояний задается случайным образом.


In [1]:
import numpy as np

Функция minDist находит минимальное значение элемента в массиве dist, который функция получает на входе, и возвращает его индекс. 
dist содержит в себе данные расстояний между пунктом отправления и всеми остальными городами. 
В visited_set помечены вершины графа, которые уже были рассмотрены.

In [2]:
def minDist(dist, visited_set):
    min_val = 9999999
    min_index = 0
    for v in range(len(dist)):
        if dist[v] < min_val and visited_set[v] == False:
            min_val = dist[v]
            min_index = v
    return min_index

Функция newGraph создает рандомную симметричную матрицу размерности NxN с нулями по диагонали.
Встроенная функция tril формирует нижнюю треугольную матрицу из рандомной матрицы rand_M, после чего к ней прибавляется эта же матрица, только транспонированная, а  k равное -1 позволяет оставить нули на диагонали.

In [3]:
def newGraph(N):
    rand_M = np.random.randint(1,200,size=(N,N))
    graph = np.tril(rand_M, -1) + np.tril(rand_M, -1).T
    return graph

Функция returnPath принимает на вход массив, полученный в ходе выполнения алгоритма Дейкстры, в котором хранятся вершины с кратчайших путей в обратном порядке. n1 и n2 - города, между которыми осуществляется поиск кратчайшего маршрута.
Пока мы не находим в массиве пункт отправления, мы продалжаем его "раскручивать": то есть мы начинаем с элемента на (n2 - 1) - ой позиции, в котором содержится индекс  предшествующего ему города, с кратчайшим маршрутом, действие продолжается до тех пор, пока мы не находим пункт отправления.
Для простоты восприятия добавляем к индексу единицу.

In [4]:
def returnPath(path, n1, n2):
    path_n1_n2 = [] 
    while n1 != n2:
        i = 0
        path_n1_n2.append(n2)
        n2 = path[n2-1]+1
        i += 1
    path_n1_n2.append(n1)
    return path_n1_n2[::-1]    

В функция Dijkstra реализован алгоритм Дейкстры поиска кратчайшего маршрута.
На входе функция получает:
N - количество городов 
n1 и n2 - города, между которыми нужно найти кратчайший маршрут.
Снчала строится матрица расстояний размера NxN, в которой указаны расстояния между городами с соответствующими номерами строк и столбцов, то есть из растояние между n1 и n2 равно значению Matrix[n1,n2] или Matrix[n2,n1].
Массив visited_set изначально заполняется значениями False (эти вершины графа (города) ещё не были исследованы), в ходе выполнения индексы исследованных точек изменяются на True.
dist - массив кратчайших расстояний, изначально равен значениям между пунктом отправления и остальными горадами.
path - массив с индесами городов, из которых найдены кратчайшие маршруты.
Первым делом находится индекс минимального элемента в массиве dist. После чего начинается анализ кратчайшего маршрута, если расстояние через точку u меньше найденного ранее, то значение в массиве dist изменяется и точка u помечается как посещенная.
В итоге выводится кратчайший маршрут между n1 и n2.

In [5]:
def Dijkstra(N, n1, n2):
    graph = newGraph(N)
    print('Матрица расстояний:\n', graph)
    visited_set = [False] * N
    dist = graph[n1 - 1]
    path = [n1-1] * N
    visited_set[n1 - 1] = True
    l = len(graph[n1])
    for i in range(l):
        u = minDist(dist, visited_set)
        for v in range(l):
            if graph[u][v] > 0 and visited_set[u] == False and dist[v] > dist[u] + graph[u][v]:
                dist[v] = dist[u] + graph[u][v]
                path[v] = u
        visited_set[u] = True
    print('Кратчайшие расстояния между n1 и остальными городами:\n', dist)    
    print('Кратчайший маршрут между n1 и n2:\n', returnPath(path, n1, n2))

In [7]:
Dijkstra(5, 1, 5)

Матрица расстояний:
 [[  0 182 119  76 121]
 [182   0 157  21 159]
 [119 157   0  91   1]
 [ 76  21  91   0  27]
 [121 159   1  27   0]]
Кратчайшие расстояния между n1 и остальными городами:
 [  0  97 104  76 103]
Кратчайший маршрут между n1 и n2:
 [1, 4, 5]
